=== blockprotocol/blockprotocol/apps/site/public/schemas/block-metadata.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BlockMetadataRepository": {
      "anyOf": [
        {
          "properties": {
            "directory": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "url"
          ],
          "type": "object"
        },
        {
          "type": "string"
        }
      ]
    },
    "BlockType": {
      "properties": {
        "entryPoint": {
          "enum": [
            "custom-element",
            "html",
            "react"
          ],
          "type": "string"
        },
        "tagName": {
          "type": "string"
        }
      },
      "required": [
        "entryPoint"
      ],
      "type": "object"
    },
    "BlockVariant": {
      "properties": {
        "description": {
          "type": [
            "null",
            "string"
          ]
        },
        "examples": {
          "anyOf": [
            {
              "items": {
                "$ref": "#/definitions/JsonObject"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "icon": {
          "type": [
            "null",
            "string"
          ]
        },
        "name": {
          "type": "string"
        },
        "properties": {
          "$ref": "#/definitions/JsonObject"
        }
      },
      "required": [
        "name",
        "properties"
      ],
      "type": "object"
    },
    "JsonArray": {
      "items": {
        "$ref": "#/definitions/JsonValue"
      },
      "type": "array"
    },
    "JsonObject": {
      "additionalProperties": {
        "$ref": "#/definitions/JsonValue"
      },
      "type": "object"
    },
    "JsonValue": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "boolean"
        },
        {
          "type": "number"
        },
        {
          "type": "string"
        },
        {
          "items": {
            "$ref": "#/definitions/JsonValue"
          },
          "type": "array"
        },
        {
          "$ref": "#/definitions/JsonObject"
        }
      ]
    }
  },
  "properties": {
    "author": {
      "description": "The name of the author of the block",
      "type": [
        "null",
        "string"
      ]
    },
    "blockType": {
      "$ref": "#/definitions/BlockType",
      "description": "The type of block this is (e.g. custom element, React)"
    },
    "commit": {
      "description": "The commit hash of the source this block was built from. If specified, 'repository' must also be specified.",
      "type": "string"
    },
    "description": {
      "description": "A short description of the block, to help users understand its capabilities",
      "type": [
        "null",
        "string"
      ]
    },
    "devReloadEndpoint": {
      "description": "URL of a web socket that reports updates in locally developed blocks. To be used by EAs to auto reload.",
      "type": [
        "null",
        "string"
      ]
    },
    "displayName": {
      "description": "The display name used for a block",
      "type": [
        "null",
        "string"
      ]
    },
    "examples": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/definitions/JsonObject"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "description": "A list of examples property objects which comply with the block's schema, for demonstration purposes"
    },
    "externals": {
      "$ref": "#/definitions/JsonObject",
      "description": "The dependencies a block relies on but expects the embedding application to provide, e.g. { \"react\": \"^18.0.0\" }"
    },
    "icon": {
      "description": "An icon for the block, to be displayed when the user is selecting from available blocks (as well as elsewhere as appropriate, e.g. in a website listing the block).",
      "type": [
        "null",
        "string"
      ]
    },
    "image": {
      "description": "A preview image of the block for users to see it in action before using it. This would ideally have a 3:2 width:height ratio and be a minimum of 900x1170px.",
      "type": [
        "null",
        "string"
      ]
    },
    "license": {
      "description": "The license the block is made available under (e.g. MIT).",
      "type": [
        "null",
        "string"
      ]
    },
    "name": {
      "description": "A unique, slugified name for the block.",
      "type": "string"
    },
    "protocol": {
      "description": "The applicable block protocol version, e.g. 0.3",
      "type": "string"
    },
    "repository": {
      "anyOf": [
        {
          "$ref": "#/definitions/BlockMetadataRepository"
        },
        {
          "type": "null"
        }
      ],
      "description": "Specify the place where your block's code lives. This is helpful for people who want to explore the source, or contribute to your block's development."
    },
    "schema": {
      "description": "The versioned URL to the block's schema, e.g. https://blockprotocol.org/@blockprotocol/types/entity-type/thing/v/2",
      "type": "string"
    },
    "source": {
      "description": "The path or URL to the entrypoint source file (e.g. index.html, index.js).",
      "type": "string"
    },
    "variants": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/definitions/BlockVariant"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "description": "A list which represents different variants of the block that the user can create."
    },
    "version": {
      "description": "The version of the block, which should use semantic versioning (@see https://semver.org/).",
      "type": "string"
    }
  },
  "required": [
    "blockType",
    "name",
    "protocol",
    "schema",
    "source",
    "version"
  ],
  "type": "object"
}

=== blockprotocol/blockprotocol/libs/block-template-html/block-metadata.json
{
  "name": "html-block",
  "version": "0.0.0",
  "description": "Block Protocol block template for an HTML element-based block",
  "author": "HASH",
  "license": "MIT",
  "schema": "https://blockprotocol.org/@blockprotocol/types/entity-type/thing/v/2",
  "variants": [],
  "blockType": {
    "entryPoint": "html"
  },
  "protocol": "0.3",
  "displayName": "Template",
  "icon": "public/omega.svg",
  "image": "public/block-preview.png",
  "source": "app.html"
}
