=== blockprotocol/blockprotocol/apps/site/public/types/modules/graph/0.3/schema/property-type.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
  "title": "Property Type",
  "description": "Specifies the structure of a Block Protocol property type",
  "type": "object",
  "properties": {
    "schema": {
      "type": "string",
      "const": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type"
    },
    "kind": {
      "const": "propertyType"
    },
    "$id": {
      "$ref": "https://blockprotocol.org/types/modules/graph/0.3/schema/versioned-url"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "oneOf": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/propertyValues"
      }
    }
  },
  "required": [
    "$schema",
    "kind",
    "$id",
    "title",
    "oneOf"
  ],
  "additionalProperties": false,
  "$defs": {
    "propertyValues": {
      "$id": "propertyValues",
      "title": "propertyValues",
      "description": "The definition of potential property values, either references to data types, objects made up of more property types, or an array where the items are defined from a set of other property values definitions.",
      "oneOf": [
        {
          "$ref": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type-reference"
        },
        {
          "title": "propertyObjectValue",
          "type": "object",
          "properties": {
            "type": {
              "const": "object"
            },
            "properties": {
              "$ref": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type-object"
            },
            "minimumProperties": 1,
            "additionalProperties": {
              "type": "boolean",
              "const": false
            }
          },
          "required": [
            "type",
            "properties",
            "additionalProperties"
          ],
          "additionalProperties": false
        },
        {
          "title": "propertyArrayValue",
          "type": "object",
          "properties": {
            "type": {
              "const": "array"
            },
            "items": {
              "type": "object",
              "properties": {
                "oneOf": {
                  "type": "array",
                  "items": {
                    "$ref": "#/$defs/propertyValues"
                  },
                  "minItems": 1
                }
              },
              "required": [
                "oneOf"
              ],
              "additionalProperties": false
            },
            "minItems": {
              "type": "integer",
              "minimum": 0
            },
            "maxItems": {
              "type": "integer",
              "minimum": 0
            }
          },
          "required": [
            "type",
            "items"
          ],
          "additionalProperties": false
        }
      ]
    }
  }
}

=== blockprotocol/blockprotocol/libs/@blockprotocol/type-system/crate/tests/data/property_type/user_id_v1.json
{
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
  "kind": "propertyType",
  "$id": "https://blockprotocol.org/@alice/types/property-type/user-id/v/1",
  "title": "User ID",
  "oneOf": [
    {
      "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1"
    }
  ]
}

=== blockprotocol/blockprotocol/libs/@blockprotocol/type-system/crate/tests/data/property_type/name.json
{
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
  "kind": "propertyType",
  "$id": "https://blockprotocol.org/@alice/types/property-type/name/v/1",
  "title": "Name",
  "oneOf": [
    {
      "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1"
    }
  ]
}

=== blockprotocol/blockprotocol/libs/@blockprotocol/type-system/crate/tests/data/property_type/contact_information.json
{
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
  "kind": "propertyType",
  "$id": "https://blockprotocol.org/@alice/types/property-type/contact-information/v/1",
  "title": "Contact Information",
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "https://blockprotocol.org/@blockprotocol/types/property-type/email/": {
          "$ref": "https://blockprotocol.org/@blockprotocol/types/property-type/email/v/1"
        },
        "https://blockprotocol.org/@blockprotocol/types/property-type/phone-number/": {
          "$ref": "https://blockprotocol.org/@blockprotocol/types/property-type/phone-number/v/1"
        }
      },
      "required": [
        "https://blockprotocol.org/@blockprotocol/types/property-type/email/"
      ]
    }
  ]
}

=== blockprotocol/blockprotocol/libs/@blockprotocol/type-system/crate/tests/data/property_type/contrived_property.json
{
  "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
  "kind": "propertyType",
  "$id": "https://blockprotocol.org/@alice/types/property-type/contrived-property/v/1",
  "title": "Contrived Property",
  "oneOf": [
    {
      "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/number/v/1"
    },
    {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/number/v/1"
          }
        ]
      },
      "maxItems": 4
    }
  ]
}
